In [1]:
import PuzzleTools

In [2]:
import Collective

In [3]:
words = PuzzleTools.Wordsets.unixwords()[1:100:end];

In [16]:
reload("Collective")

In [17]:
c = Collective.Corpus(words)

Collective.Corpus(Collective.Feature[Collective.ContainsLetter('a'),Collective.ContainsLetter('b'),Collective.ContainsLetter('c'),Collective.ContainsLetter('d'),Collective.ContainsLetter('e'),Collective.ContainsLetter('f'),Collective.ContainsLetter('g'),Collective.ContainsLetter('h'),Collective.ContainsLetter('i'),Collective.ContainsLetter('j')  …  Collective.ScrabbleScore(21),Collective.ScrabbleScore(22),Collective.ScrabbleScore(23),Collective.ScrabbleScore(24),Collective.ScrabbleScore(25),Collective.ScrabbleScore(26),Collective.ScrabbleScore(27),Collective.ScrabbleScore(28),Collective.ScrabbleScore(29),Collective.ScrabbleScore(30)],[0.615515,0.160237,0.365833,0.267062,0.672319,0.0962272,0.174226,0.234421,0.615515,0.0135651  …  0.0360322,0.0296736,0.0254345,0.0216193,0.0131412,0.0101738,0.0127173,0.00720644,0.00635863,0.00423908])

In [22]:
score_dist = Dict{Int, Int}()
for word in words
    score = Collective.scrabble_score(word)
    score_dist[score] = get(score_dist, score, 0) + 1
end

In [26]:
scores = zeros(maximum(keys(score_dist)))
for (score, count) in score_dist
    scores[score] = count
end

In [29]:
F = cumsum(scores / sum(scores))

46-element Array{Float64,1}:
 0.000423908
 0.000423908
 0.000847817
 0.00593472 
 0.0131412  
 0.0258584  
 0.0517168  
 0.0796948  
 0.120814   
 0.175498   
 0.236965   
 0.303095   
 0.364561   
 ⋮          
 0.995761   
 0.997033   
 0.997457   
 0.998728   
 0.998728   
 0.999152   
 0.999152   
 0.999152   
 0.999576   
 0.999576   
 0.999576   
 1.0        

In [30]:
scores_exp = zeros(46)
scores_exp[14] = 5

5

In [31]:
Fn = cumsum(scores_exp / sum(scores_exp))

46-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [44]:
A = (Fn, F, n) -> n * sum((Fn[i] - F[i])^2 / (F[i] * (1 - F[i])) for i in 1:(length(F) - 1))

(::#11) (generic function with 1 method)

In [45]:
A(Fn, F, 5)

34.259516512945844

In [46]:
A([0, 1], [0.5, 1], 2)

2.0

In [21]:
d1s2 = ["leveraged", "sizes", "tuxedo", "lynx", "lightly", "crocodile", "triumph"]
sort(Collective.analyze(c, d1s2))[1:10]

10-element Array{Collective.FeatureResult,1}:
 Collective.FeatureResult(Collective.ScrabbleScore(14),Bool[true,true,true,true,true,true,true],1.00936e-8)            
 Collective.FeatureResult(Collective.LetterAtIndex('l',1),Bool[true,false,false,true,true,false,false],0.000598249)    
 Collective.FeatureResult(Collective.LetterAtIndex('z',3),Bool[false,true,false,false,false,false,false],0.00883437)   
 Collective.FeatureResult(Collective.ContainsLetter('a'),Bool[true,false,false,false,false,false,false],0.0139192)     
 Collective.FeatureResult(Collective.ContainsLetter('x'),Bool[false,false,true,true,false,false,false],0.0154881)      
 Collective.FeatureResult(Collective.AlternatesConsonantVowel(),Bool[true,true,true,false,false,false,false],0.0178617)
 Collective.FeatureResult(Collective.LetterAtIndex('e',4),Bool[true,true,true,false,false,false,false],0.0260784)      
 Collective.FeatureResult(Collective.LetterAtIndex('x',4),Bool[false,false,false,true,false,false,false],0.0289268